### ISSUE TITLE
Add missing localisations

### ISSUE THREAD

**Issue by wookiefriseur** [manavortex/FurnitureCatalogue#40]
_Moved here from_ https://github.com/BerylBones/FurnitureCatalogue/issues/7

---

### Description
Currently only small parts of the localisation files are translated and there are some hardcoded English strings in the code.

- https://github.com/BerylBones/FurnitureCatalogue/blob/093d8723ca4653a881ed3dc47be218ca69991c32/locale/de.lua#L46
- https://github.com/BerylBones/FurnitureCatalogue/blob/093d8723ca4653a881ed3dc47be218ca69991c32/xml/FurnitureCatalogue.xml#L26
- and so on

### Priority
🟩 Probably low for all officially supported languages, because the recipes, furnishings and material are translated through zos functions.
Not sure about JP and RU though, those probably require an extra localisation library for game strings.

`Version: 4.323`

**Comment by manavortex** [comment]
If you can use default game strings and -functions for GUI elements, then that should take care of the problem. 

Other than that, the last time I checked, the UI lib (jeez, which one has it been? It's been so long) already supported UTF-8, so that should take care of Japanese/Russian chars. You'd just need a volunteer to generate you a language file. 

The way I initially hooked up the translations (best practice, Ayantir walked me through it - ah, I miss him) is that English is read and registered first, and then will be overwritten with any entries from the localized file. I have no idea if you changed it around since, but that way, translations will always default to English if no localized string is given.

**Comment by wookiefriseur** [comment]
> Other than that, the last time I checked, the UI lib (jeez, which one has it been? It's been so long) already supported UTF-8, so that should take care of Japanese/Russian chars. You'd just need a volunteer to generate you a language file.
Nice, good to know. Text does not change much, so I can probably just use the Google-Docs crowdsource approach. 😄 

> The way I initially hooked up the translations (best practice, Ayantir walked me through it - ah, I miss him) is that English is read and registered first, and then will be overwritten with any entries from the localized file. I have no idea if you changed it around since, but that way, translations will always default to English if no localized string is given.
Oh yeah, Ayantir rings a bell.. I associate the name with a turtle profile pic. Yeah, `en` is always the fallback, that works well. Just have to look for any hardcoded stragglers that have to be added to the list.

**Comment by wookiefriseur** [comment]
Changes are live as of #147 . Most of the hardcoded strings are gone now.  Missing translations will be added later. Closing this :)
